// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7JcqQgLxMNt3cMwFW43lAje1eUtVQ6ZU',
    appId: '1:39966400637:web:28dce9b6b24c50b9f29114',
    messagingSenderId: '39966400637',
    projectId: 'monshaa-b498c',
    authDomain: 'monshaa-b498c.firebaseapp.com',
    storageBucket: 'monshaa-b498c.appspot.com',
    measurementId: 'G-WCNS84YGDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGZh70PRGTAUL-onezwM8muqmPN8x0nmQ',
    appId: '1:39966400637:android:ed1a0250bf897a60f29114',
    messagingSenderId: '39966400637',
    projectId: 'monshaa-b498c',
    storageBucket: 'monshaa-b498c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe_Kg_y70kV1DMHYzJsCykC9TyuIfOZgk',
    appId: '1:39966400637:ios:d30f37df81c1abfef29114',
    messagingSenderId: '39966400637',
    projectId: 'monshaa-b498c',
    storageBucket: 'monshaa-b498c.appspot.com',
    iosBundleId: 'com.example.aplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe_Kg_y70kV1DMHYzJsCykC9TyuIfOZgk',
    appId: '1:39966400637:ios:eed43f1798e70d5ff29114',
    messagingSenderId: '39966400637',
    projectId: 'monshaa-b498c',
    storageBucket: 'monshaa-b498c.appspot.com',
    iosBundleId: 'com.example.aplication.RunnerTests',
  );
}
